# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ 'master', 'update' ]
  pull_request:
    branches: [ 'master', 'update' ]

jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        java-version: [ 21 ]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.java-version }}"
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: 'temurin'
          cache: 'maven'
      - name: Install VentureChat
        run: mvn install:install-file -Dfile=libs/VentureChat-3.7.1.jar -DgroupId=mineverse.Aust1n46.chat -DartifactId=VentureChat -Dversion=3.7.1 -Dpackaging=jar -f pom.xml
      - name: Build with Maven
        run: ./mvnw -B -U package --file pom.xml
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleClans
          path: target/SimpleClans-*.jar
